database:
  AMASS_path: "./AMASS" # path to the database
  AMASS_cache_path: "./AMASS_cache"
  fps: 120
  left_foot_index: 7
  right_foot_index: 8
  loss_weight:
    cur_root_xz_velocity: 1.0
    cur_root_y_angular_velocity: 1.0
    cur_foot_relative_position: 5.0
    future_root_xz_position: 7.0

motion_matching:
  init_seq_name: "0005_Walking001_stageii.npz"
  init_seq_idx: 100
  consider_trajectory_interval: 20
  consider_trajectory_range: 100 # consider 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 frames trajectories
  search_interval: 30 # search interval for motion matching
  keypoint_list:
    - [0,0]
    - [10, 0]
    - [0, 10]
    - [10, 10]
  half_life: 0.2
  max_iter: 300

visualization:
  down_sample_rate: 5 # down sample rate for visualization, visualizing every 5 frames
